
name: BuildTestWasm

on:
  push:
    branches:
      - rust-wasm

jobs:
  build-wasm:
    
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain, tools, and restore cache
        uses: ./.github/workflows/actions/toolchain-and-cache
        with:
          cache-version: ${{ secrets.CACHE_VERSION }}-wasm
          cargo-tools: wasm-pack

      - name: Build 'rust-wasm' library
        shell: bash
        run: |
          cd src-wasm
          cargo build
          wasm-pack build --target web
