
name: Download artifact

on:
  push:
    branches:
      - reuse_artifact

jobs:
  produce_artifact:
    name: Produce and upload artifact
    runs-on: ubuntu-latest
    steps:
      - name: Creation du fichier
        run: |
          echo "Hello someone!" > hello.txt

      - name: Mise en archive du fichier
        uses: actions/upload-artifact@v3
        with:
          name: uploaded_file
          path: hello.txt

  reuse_artifact:
    name: Produce and upload artifact
    runs-on: ubuntu-latest
    needs: produce_artifact
    steps:
      - name: Récupération de l'artifact
        uses: actions/download-artifact@v3

      - name: Affichage du contenu        
        run: |
          echo "Contenu de $(pwd)"
          ls

          echo "Contenu de uploaded_file"
          ls uploaded_file
          cat uploaded_file/hello.txt