
name: Hello world

on:
  push:
    branches:
      - hello*

jobs:
  say_hello:
    name: Hello
    runs-on: ubuntu-latest
    steps:
      - name: Test docker
        run: |
          echo "Hello John!"
