name: GitHub Pages Publish

on:
  push:
    branches: [ spike_doc ]


jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v3
#      
#    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
#    # from https://github.com/manoelcampos/asciidoctor-ghpages-action
#    - name: asciidoctor-ghpages
#      uses: manoelcampos/asciidoctor-ghpages-action@v2
#      with:
#        pdf_build: true
#        asciidoctor_params: --attribute=nofooter
#        # adoc_file_ext: .ascii # default is .adoc
#        source_dir: docs/ # default is .
#        # slides_build: true
#        #pre_build: python pre_build.py
#        # post_build:

#  publish-asciidoc:
#    runs-on: ubuntu-latest
#    container:
#      image: asciidoctor/docker-asciidoctor
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Generate HTML
#        run: |
#          INPUT_PATH=asciidocs
#          asciidoctor -D docs -R $INPUT_PATH $(find $INPUT_PATH -type f -name "[^_]*.adoc")
#
#      - name: publish jekyll site in gh pages
      

# Set -R to keep subfolder in output files.
# It's possible to include files that are not in docs
# To find all files that not start by `_` find docs -name "[^_]*.adoc"
# To list all files that not start by '_': $(find $INPUT_PATH -type f -name "[^_]*.adoc")


  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    # from https://github.com/manoelcampos/asciidoctor-ghpages-action
    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        # pdf_build: true
        asciidoctor_params: --attribute=nofooter
        adoc_file_ext: "[^_]*.adoc" # default is .adoc
        source_dir: asciidocs/ # default is .
        # slides_build: true
        # pre_build: python pre_build.py
        # post_build: