
name: Publish doc pages

on:
  push:
    branches: [ master ]

jobs:
#  merge_develop_to_publish:
  # make_package: (test + doc)
  # make_release: (or not)
  # publish_doc: (if no src modify)

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: pages

      -name: Show history
        run: git log --oneline --graph master pages

      - name: Configure Git user
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Merge from master
        run: git merge origin/master --allow-unrelated-histories -m "Merge from master"

      - name: Copy docs
        run: |
          rm -Rf docs
          cp -R builded_docs docs

      - name: Commit docs
        run: |
          git add docs
          git commit -m "New doc"
          git push -f