name: GitHub Pages Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    # from https://github.com/manoelcampos/asciidoctor-ghpages-action
    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        pdf_build: true
        asciidoctor_params: --attribute=nofooter
        # adoc_file_ext: .ascii # default is .adoc
        source_dir: docs/ # default is .
        # slides_build: true
        pre_build: python pre_build.py
        # post_build: