
name: Publish doc pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
#  merge_develop_to_publish:
  # make_package: (test + doc)
  # make_release: (or not)
  # publish_doc: (if no src modify)

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: pages

      - name: Show history
        run: |
          echo "master and pages tree"
          git log --oneline --graph origin/master pages

      - name: Pages history
        run: |
          echo "pages history"
          git log --pretty=oneline pages | tail -n 15

      - name: Origin Pages history
        run: |
          echo "origin/pages history"
          git log --pretty=oneline origin/pages | tail -n 15

      - name: Configure Git user
        run: |
          git config user.email "actions@noreply.github.com"
          git config user.name "GitHub Actions"

      - name: Merge from master
        run: git merge origin/master --allow-unrelated-histories -m "Merge from master"

      - name: Copy docs
        run: |
          rm -Rf docs
          cp -R builded_docs docs

      - name: Retrieve diff
        id: git_diff
        run: |
          echo "===== git diff ===="
          git diff
          echo "================="
          echo "::set-output name=DOC_DIFF::$(git diff)"
          echo "Diff: ${{ steps.git_diff.outputs.DOC_DIFF }}"

      - name: Check diff
        if: ${{ steps.git_diff.outputs.DOC_DIFF }} == ''
        run: |
          echo "==== NO DIFF ===="
          echo "=> ${{ steps.git_diff.outputs.DOC_DIFF }}"

      - name: Check not diff
        if: ${{ steps.git_diff.outputs.DOC_DIFF }} != ''
        run: |
          echo "==== DIFF ===="
          echo "=> ${{ steps.git_diff.outputs.DOC_DIFF }}"

      - name: Commit docs
        run: |
          echo "==== GIT DIFF ===="
          echo "${{ steps.git_diff.outputs.DOC_DIFF }}"
          echo "=================="

          git add docs
          git commit -m "New doc"
          git push -f