name: Release # Workflow name displayed on GitHub

on:
  workflow_dispatch: # Trigger manually
    branches: main # Branch on which the workflow will run

jobs:
  new-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # Checkout our working repository
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Prepare Release
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
         
          last_release_tag=`git describe --abbrev=0 --tags`
          echo "Last release tag: $last_release_tag"
#          release_note=`./gradlew getChangelog --console=plain -q --no-header --no-summary`
          release_note="Toto"
          gh release create $last_release_tag -n $release_note ./build/libs/*
