
name: Make a release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Make a release
      run: echo "Make a release"

    - name: Push a release
      run: |
        echo "New release" >> release.adoc
        git add release.adoc
        git commit -m "New release"
        git push -f