
name: Hello world

on:
  push:
    branches:
      - spike

env:
  root_branch: 'spike'

jobs:
  check_prerequisites:
    name: Check the prerequisites
    runs-on: ubuntu-latest

    steps:
      - name: check branch
        run: |
          NB=`1`
          echo "NB: $NB"

    outputs:
      IS_BRANCH_EXIST: ${{steps.check_prerequisites.outputs.NB}}

  first_job:
    name: Spike on branch
    needs: check_prerequisites
    if: needs.check_prerequisites.outputs.NB == 1

    runs-on: ubuntu-latest
    steps:
      - name: Test docker
        run: |
          echo "Build"
