
name: Hello world

on:
  push:
    branches:
      - spike

env:
  root_branch: 'spike'

jobs:
  check_prerequisites:
    name: Check the prerequisites
    runs-on: ubuntu-latest

    steps:
      - name: check branch
        run: |
          NB=`echo 1`
          echo "NB: $NB"

    outputs:
      NB: ${{steps.check_prerequisites.outputs.NB}}

  first_job:
    name: First job
    needs: check_prerequisites
    if: needs.check_prerequisites.outputs.NB == "1"

    runs-on: ubuntu-latest
    steps:
      - name: Init env
        run: |
          echo "Create branch"

  second_job:
    name: Second job
    needs: first_job
    if: always()

    runs-on: ubuntu-latest
    steps:
      - name: Run job
        run: |
          echo "Build"
